
package gr.uoa.di.std09112.std08169.k23;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WebServiceAthroisthsImplService", targetNamespace = "http://k23.std08169.std09112.di.uoa.gr/", wsdlLocation = "http://localhost:1234/?wsdl")
public class WebServiceAthroisthsImplService
    extends Service
{

    private final static URL WEBSERVICEATHROISTHSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICEATHROISTHSIMPLSERVICE_EXCEPTION;
    private final static QName WEBSERVICEATHROISTHSIMPLSERVICE_QNAME = new QName("http://k23.std08169.std09112.di.uoa.gr/", "WebServiceAthroisthsImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:1234/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICEATHROISTHSIMPLSERVICE_WSDL_LOCATION = url;
        WEBSERVICEATHROISTHSIMPLSERVICE_EXCEPTION = e;
    }

    public WebServiceAthroisthsImplService() {
        super(__getWsdlLocation(), WEBSERVICEATHROISTHSIMPLSERVICE_QNAME);
    }

    public WebServiceAthroisthsImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICEATHROISTHSIMPLSERVICE_QNAME, features);
    }

    public WebServiceAthroisthsImplService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICEATHROISTHSIMPLSERVICE_QNAME);
    }

    public WebServiceAthroisthsImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICEATHROISTHSIMPLSERVICE_QNAME, features);
    }

    public WebServiceAthroisthsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceAthroisthsImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceAthroisths
     */
    @WebEndpoint(name = "WebServiceAthroisthsImplPort")
    public WebServiceAthroisths getWebServiceAthroisthsImplPort() {
        return super.getPort(new QName("http://k23.std08169.std09112.di.uoa.gr/", "WebServiceAthroisthsImplPort"), WebServiceAthroisths.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceAthroisths
     */
    @WebEndpoint(name = "WebServiceAthroisthsImplPort")
    public WebServiceAthroisths getWebServiceAthroisthsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://k23.std08169.std09112.di.uoa.gr/", "WebServiceAthroisthsImplPort"), WebServiceAthroisths.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICEATHROISTHSIMPLSERVICE_EXCEPTION!= null) {
            throw WEBSERVICEATHROISTHSIMPLSERVICE_EXCEPTION;
        }
        return WEBSERVICEATHROISTHSIMPLSERVICE_WSDL_LOCATION;
    }

}
