
package gr.uoa.di.std09112.std08169.k23;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServiceAthroisths", targetNamespace = "http://k23.std08169.std09112.di.uoa.gr/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceAthroisths {


    /**
     * 
     * @param device
     * @param networkData
     */
    @WebMethod
    @RequestWrapper(localName = "setNetworkData", targetNamespace = "http://k23.std08169.std09112.di.uoa.gr/", className = "gr.uoa.di.std09112.std08169.k23.SetNetworkData")
    @ResponseWrapper(localName = "setNetworkDataResponse", targetNamespace = "http://k23.std08169.std09112.di.uoa.gr/", className = "gr.uoa.di.std09112.std08169.k23.SetNetworkDataResponse")
    @Action(input = "http://k23.std08169.std09112.di.uoa.gr/WebServiceAthroisths/setNetworkDataRequest", output = "http://k23.std08169.std09112.di.uoa.gr/WebServiceAthroisths/setNetworkDataResponse")
    public void setNetworkData(
        @WebParam(name = "device", targetNamespace = "")
        String device,
        @WebParam(name = "networkData", targetNamespace = "")
        NetworkData networkData);

}
